apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: hello-python:v1
          imagePullPolicy: Never
          env:
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: hello-config
                  key: GREETING
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: hello-secret
                  key: API_KEY
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hello-pvc
