{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hello-chart.fullname" . }}-pvc
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeName: {{ include "hello-chart.fullname" . }}-pv
{{- end }}
